name: hanumanji
description: Hanuman Chalisa

version: 1.0.1+2

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.15.1
  cupertino_icons: ^1.0.2
  firebase_admob: ^0.11.0
  firebase_analytics: ^7.0.0
  launch_review: ^2.0.0
  share: ^0.6.5+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
  flutter_rename_app: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - hanumanji.jpg
    - hanuman.png

flutter_rename_app:
  application_name: HanumanJi
  dart_package_name: hanumanji
  application_id: com.fz.hanumanji
  bundle_id: com.fz.hanumanji
  android_package_name: com.fz.hanumanji

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/hanuman.png"
